@startuml US

title Lvl 2 - Create Truck

autonumber

actor "Fleet Manager" as FM
participant "<< Container (C4) >> \n SPA" as S
participant "<< Container (C4) >> \n Logistics" as LG


activate FM
FM -> S : Selects the option to create a truck
activate S
S --> FM : Requests the necessary data
deactivate S

FM -> S : Inserts the requested data.
activate S

S -> LG : POST /api/Trucks
activate LG

LG -> LG : save(TruckData)

LG -> S : HTTP 201 Created
deactivate LG

S --> FM : Validates the data and informs of operation success.

deactivate S

deactivate FM

@enduml