@startuml

title Lvl 1 - Delete Truck

autonumber

actor "Fleet Manager" as FM
actor "<< Container >> \n Visual Interface" as SYS

activate FM
FM -> SYS : Asks to delete a truck.
activate SYS
SYS --> FM : Ask to choose wich truck you want to delete.
deactivate SYS

FM -> SYS : Chooses the truck.
activate SYS
SYS --> FM : Validates the data and requests confirmation.
deactivate SYS

FM -> SYS : Confirms the information.
activate SYS
SYS --> FM : Saves the data and informs of operation success.
deactivate SYS

deactivate FM

@enduml