@startuml

title Lvl 2 - Delete Truck

autonumber

actor "Fleet Manager" as FM
actor "<< Container >> \n Visual Interface" as SYS
actor "<< Container >> \n TruckDataMaster" as TDM


activate FM
FM -> SYS : Asks to delete a truck.
activate SYS
SYS --> FM : Ask to choose wich truck you want to delete.
deactivate SYS

FM -> SYS : Choose the truck.
activate SYS

SYS -> TDM : GET truck/{matricula}
activate TDM

TDM -> SYS : truck(JSON)
deactivate TDM

SYS --> FM : Validates the data and requests confirmation.
deactivate SYS


FM -> SYS : Confirms the information.
activate SYS

SYS -> TDM : DELETE truck/{matricula}
activate TDM
TDM --> SYS
deactivate TDM

SYS --> FM : Saves the data and informs of operation success.
deactivate SYS


deactivate FM

@enduml