@startuml USA04_3

title SD - Delete Warehouse

autonumber

participant "API" as API
participant " WarehouseController" as C
participant "Warehouse Service" as S
participant "WarehouseRepository" as R
participant "UnitOfWork" as U

activate API
-> API : DELETE (warehouse_id)
API -> C : HardDelete(warehouse_id)
activate C
C -> S : DeleteAsync(warehouse_id)
activate S
S -> R : GetByIdAsync(WarehouseId)
activate R
R -> R : Fetch(WarehouseId)
R --> S : Warehouse
deactivate R
S -> R : Remove(warehouse)
activate R
R --> S
deactivate R
S -> U : CommitAsync
activate U
U --> S
deactivate U
S --> C : DeletedWarehouse(WarehouseDto)
deactivate S
C --> API : Response Code 200
deactivate C
deactivate API