@startuml USA02

title Lvl 2 - List & Page Packagings

autonumber

actor "Logistics Manager" as LM
participant "<< Container (C4) >> \n SPA" as S
participant "<< Container (C4) >> \n SSO Authetication" as SSO
participant "<< Container (C4) >> \n AuthGuard" as AG
participant "<< Container (C4) >> \n LogisticsModule" as LMD


activate LM
LM -> S : Clicks sign-in with Google button
activate S
S -> SSO : Logs in with a Google Account
activate SSO
SSO --> SSO : Checks if the email is registered
SSO --> S : Email is correct
deactivate SSO
S --> LM : Shows Logistic Manager Features
deactivate S
LM -> S : Selects the option to List Packagings by page
activate S
S --> AG : Checks if this user has Authorization to view this page
activate AG
AG -> AG : CanActivateChild()
AG --> S : Authorized
deactivate AG

S -> LMD : GET /api/packagings
activate LMD

LMD -> S : packagings(JSON)
deactivate LMD

S --> LM : Show the list with all the packagings by page
deactivate S
deactivate LM

@enduml