@startuml USA02

title Lvl 1 - List & Page Packagings


autonumber
actor "Logistics Manager" as LM
participant "<< Container >> \n SPA" as S

activate LM
LM -> S : Clicks sign-in with Google button
activate S
S --> LM : Shows Logistic Manager Features
deactivate S
LM -> S : Selects the option to List Packagings
activate S
S --> LM : Show the list with all the packagings
deactivate S

deactivate LM

@enduml