@startuml USA02

title Lvl 1 - List Route Planning


autonumber
actor "Logistics Manager" as LM
participant "<< Container >> \n SPA" as S

activate LM
LM -> S : Selects the option to List Route Plannings
activate S
S --> LM : Ask for the LicensePlate and Date
deactivate S

LM -> S : Selects the necessary data and click calculate button
activate S
S --> LM : Show the list with all the Route Plannings for the data selected
deactivate S

deactivate LM

@enduml