@startuml USA02

title Lvl 2 - List Route Plannings

autonumber

actor "Logistics Manager" as LM
participant "<< Container (C4) >> \n SPA" as S
participant "<< Container (C4) >> \n LogisticsModule" as LMD
participant "<< Container (C4) >> \n PlanningModule" as PMD


activate LM
LM -> S : Selects the option to List Route Plannings
activate S
S -> LMD : GET /api/trucks
activate LMD

LMD -> S : listOfTrucks(JSON)
deactivate LMD

S --> LM : Ask for the LicensePlate from the presented list and Date
deactivate S

LM -> S : Selects the necessary data and click calculate button
activate S

S -> PMD : GET /fastestSequence(date, licensePlate in URL)
activate PMD

PMD -> S : Sequence of Cities and Necessary Time (JSON)
deactivate PMD

S --> LM : Show the list of sequence of cities and necessary time for a trip
deactivate S
deactivate LM

@enduml