@startuml US

title Lvl 2 - Create Warehouse

autonumber

actor "Warehouse Manager" as WM
participant "<< Container (C4) >> \n SPA" as S
participant "<< Container (C4) >> \n WarehouseModule" as WMD


activate WM
WM -> S : Selects the option to create a warehouse
activate S
S --> WM : Requests the necessary data
deactivate S

WM -> S : Inserts the requested data.
activate S

S -> WMD : POST /api/Warehouse
activate WMD

WMD -> WMD : save(WarehouseData)

WMD -> S : HTTP 201 Created
deactivate WMD

S --> WM : Validates the data and informs of operation success.

deactivate S

deactivate WM

@enduml